default_config:
lovelace:
  mode: yaml
  resources:
    - url: http://127.0.0.1:5000/thermostat-dark-card.js
      type: module
demo:
climate:
  - platform: generic_thermostat
    name: test
    heater: input_boolean.office_heater
    target_sensor: sensor.office_feels_temp

sensor:
  - platform: template
    sensors:
      office_feels_temp:
        unit_of_measurement: "Â°C"
        value_template: "17"

input_boolean:
  office_ac:
  office_heater: